services:
  - type: web
    name: mysteria-backend
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: CLIENT_URL
        value: https://mysteria-nk8g9zwra-tonysixxs-projects.vercel.app
